# Copyright 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
CXX ?= g++

PYTHON_CONFIG ?= python-config
SOFLAGS = $(shell $(PYTHON_CONFIG) --includes --ldflags)

LIBS := gl egl x11 libpng glfw3
